/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AirStudios (https://sketchfab.com/sebbe613)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-5f9c35be31a047928eace8b415a8ee3a
Title: Earth
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Earth(props) {
  const { nodes, materials } = useGLTF("/earth/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group scale={96.724}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere1_phong1_0.geometry}
          material={materials.phong1}
          material-roughness={1}
          material-metalness={0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere1_phong1_0_1.geometry}
          material={materials.phong1}
        />
      </group>
      <group scale={97.464}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere4_lambert6_0.geometry}
          material={materials.lambert6}
          material-roughness={1}
          material-metalness={0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere4_lambert6_0_1.geometry}
          material={materials.lambert6}
        />
      </group>
      <group scale={98.098}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere5_lambert7_0.geometry}
          material={materials.lambert7}
          material-roughness={1}
          material-metalness={0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere5_lambert7_0_1.geometry}
          material={materials.lambert7}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/earth/scene.gltf");
