import { useThree } from "@react-three/fiber";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Thomas Flynn (https://sketchfab.com/nebulousflynn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nasa-cgi-moon-kit-1c496b3b57304526b5b9d1cf9c1087fc
Title: 🌑 NASA CGI Moon Kit
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Sphere } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("moon/scene.gltf");
  return (
    <group {...props} dispose={null} scale={2}>
      <group rotation={[-Math.PI / 2, 3, 0]}>
        <Sphere args={[1, 100, 100]}>
          <meshStandardMaterial
            attach="material"
            {...materials.None}
            roughness={1}
            metalness={0}
          />
        </Sphere>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
